pub mod cardiovascular;
pub mod respiratory;
pub mod muscular;
pub mod digestive;
pub mod endocrine;
pub mod nervous;
pub mod renal;
pub mod integumentary;
pub mod immune;
pub mod reproductive;
pub mod sensory;
pub mod lymphatic;
pub mod vision;
pub mod auditory;
pub mod gastrointestinal;

pub use cardiovascular::{Heart, BloodVessel, Blood};
pub use respiratory::{Lung, GasExchange, BreathingPattern};
pub use muscular::{Muscle, ContractionMechanism};
pub use digestive::{GITract, NutrientAbsorption};
pub use endocrine::{Hormone, EndocrineLandscape};
pub use nervous::{CentralNervousSystem, PeripheralNervousSystem};
pub use renal::{Kidney, Filtration};
pub use integumentary::{Skin, Hair, Nail};
pub use immune::{LymphaticSystem, WhiteBloodCell};
pub use reproductive::{MaleReproductiveSystem, FemaleReproductiveSystem};
pub use lymphatic::{LymphNodeSystem, LymphaticVesselNetwork, Lymph, Spleen, Thymus};
pub use vision::{Eye, VisualPathway, VisualAcuity};
pub use auditory::{Ear, AuditoryPathway, HearingAcuity};
